openapi: 3.0.0
servers:
  - url: https://api.imgur.com
info:
  title: Imgur API
  description: >-
    Imgur's API exposes the entire Imgur infrastructure via a standardized programmatic interface.
    Using Imgur's API, you can do just about anything you can do on imgur.com, while using your programming language of choice.
  version: 0.1.0
tags:
  - name: image
    description: Account-agnostic image endpoints.
paths:
  /3/image/{imageHash}:
    get:
      tags:
        - image
      description: Get information about an image.
      operationId: getImage
      parameters:
        - $ref: '#/components/parameters/imageHash'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ImageResponse'
    delete:
      tags:
        - image
      description: Delete an image.
      operationId: deleteImage
      parameters:
        - $ref: '#/components/parameters/imageHash'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BasicBooleanResponse'
components:
  parameters:
    imageHash:
      name: imageHash
      in: path
      required: true
      schema:
        type: string
  schemas:
    Image:
      type: object
      required:
        - ad_type
        - ad_url
        - animated
        - bandwidth
        - datetime
        - favorite
        - height
        - id
        - in_gallery
        - in_most_viral
        - is_ad
        - link
        - size
        - tags
        - type
        - views
        - width
      properties:
        account_id:
          type: integer
          format: int32
        account_url:
          type: string
        ad_type:
          type: integer
          format: int32
        ad_url:
          type: string
        animated:
          type: boolean
        bandwidth:
          type: integer
          format: int32
        deletehash:
          type: string
        datetime:
          type: integer
          format: int32
        description:
          type: string
        favorite:
          type: boolean
        height:
          type: integer
          format: int32
        id:
          type: string
        in_gallery:
          type: boolean
        in_most_viral:
          type: boolean
        is_ad:
          type: boolean
        link:
          type: string
        name:
          type: string
        nsfw:
          type: boolean
        section:
          type: string
        size:
          type: integer
          format: int32
        tags:
          type: array
          items:
            type: string
        title:
          type: string
        type:
          type: string
        views:
          type: integer
          format: int32
        vote:
          type: string
        width:
          type: integer
          format: int32
    ImageResponse:
      type: object
      required:
        - data
        - status
        - success
      properties:
        data:
          $ref: '#/components/schemas/Image'
        status:
          type: integer
          format: int32
        success:
          type: boolean
    BasicBooleanResponse:
      type: object
      required:
        - data
        - status
        - success
      properties:
        data:
          type: boolean
        status:
          type: integer
          format: int32
        success:
          type: boolean
externalDocs:
  description: Find out more about Imgur API.
  url: https://apidocs.imgur.com/
