name: tag

on:
  push:
    branches:
      - main
    paths:
      - schema.oas.yml

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: salsify/action-detect-and-tag-new-version@v2
        with:
          version-command: |-
            ruby -r yaml -e "puts YAML.load_file('schema.oas.yml').dig('info', 'version')"
