name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.8.1
        with:
          file_glob: schema.yml
      - uses: mhiew/redoc-lint-github-action@v2
        with:
          args: >-
            --skip-rule operation-4xx-response
            schema.oas.yml
