name: test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ::add-matcher::.github/matchers.json
      - uses: mhiew/redoc-lint-github-action@v2
        with:
          args: >-
            schema.oas.yml
            --format stylish
            --skip-rule operation-4xx-response
        env:
          NO_COLOR: '1'
